package com.kotva.domain.endgame;

public enum GameEndReason {
    ALL_PLAYERS_PASSED,
    ONLY_ONE_PLAYER_REMAINING,
    TILE_BAG_EMPTY_AND_PLAYER_FINISHED,
    BOARD_FULL,
    TARGET_SCORE_REACHED,
    NO_LEGAL_PLACEMENT_AVAILABLE,
    AI_RUNTIME_FAILURE,
    NORMAL_FINISH
}
